/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nmc.nust.medical.centre;
import Connection.MySqlConnection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Rehan Ramzan
 */
public class Doctor extends javax.swing.JFrame {
 
    /**
     * Creates new form Page_Doctor
     */

    
    
    
    
    
    public Doctor() {
      
        initComponents();
        
    }
     
   
    
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Dr_name = new javax.swing.JTextField();
        Dr_Id = new javax.swing.JTextField();
        Dr_address = new javax.swing.JTextField();
        Dr_specialization = new javax.swing.JTextField();
        Dr_experience = new javax.swing.JTextField();
        Dr_room = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Dr_email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Dr_phone = new javax.swing.JTextField();
        DrSave = new javax.swing.JButton();
        Dr_gender = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jLabel10.setText("jLabel10");

        jLabel11.setText("jLabel11");

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\Screen550.jpg")); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\Screen550.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.textHighlight);
        jLabel1.setText("Doctor Name ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.textHighlight);
        jLabel2.setText("Doctor ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, 30));

        jLabel3.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.textHighlight);
        jLabel3.setText("Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 80, 30));

        jLabel4.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel4.setForeground(java.awt.SystemColor.textHighlight);
        jLabel4.setText("Specialization");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 140, -1));

        jLabel5.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel5.setForeground(java.awt.SystemColor.textHighlight);
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 70, 30));

        jLabel6.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel6.setForeground(java.awt.SystemColor.textHighlight);
        jLabel6.setText("Experience");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 110, 30));

        jLabel7.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel7.setForeground(java.awt.SystemColor.textHighlight);
        jLabel7.setText("Room No.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        Dr_name.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        getContentPane().add(Dr_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 250, 25));

        Dr_Id.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        getContentPane().add(Dr_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 250, 25));

        Dr_address.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        getContentPane().add(Dr_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 250, 25));

        Dr_specialization.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        getContentPane().add(Dr_specialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 250, 25));

        Dr_experience.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        getContentPane().add(Dr_experience, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 250, 25));

        Dr_room.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        getContentPane().add(Dr_room, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 250, 25));

        jLabel8.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel8.setForeground(java.awt.SystemColor.textHighlight);
        jLabel8.setText("Email");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 60, 30));

        Dr_email.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        Dr_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dr_emailActionPerformed(evt);
            }
        });
        getContentPane().add(Dr_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 250, 25));

        jLabel9.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel9.setForeground(java.awt.SystemColor.textHighlight);
        jLabel9.setText("Contact No.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, 30));

        Dr_phone.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        Dr_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dr_phoneActionPerformed(evt);
            }
        });
        getContentPane().add(Dr_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 250, 25));

        DrSave.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\Save.png")); // NOI18N
        DrSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrSaveActionPerformed(evt);
            }
        });
        getContentPane().add(DrSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, 50));

        Dr_gender.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        Dr_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(Dr_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 250, 25));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\eraser (1).png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 60, 50));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\close.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 50, 40));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\Screen550.jpg")); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DrSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrSaveActionPerformed
         Connection con = MySqlConnection.Connect();
         Statement st;
        String ID = Dr_Id.getText();
        try {
            PreparedStatement pst = con.prepareStatement("Select * from staff where staff_id = ?");
            pst.setString(1, ID);
            ResultSet r = pst.executeQuery();
            if(r.next()){
                JOptionPane.showMessageDialog(this,"ID in Use.","Error",JOptionPane.ERROR_MESSAGE);
                Dr_Id.setText("");
            }
            else{
        String Name = Dr_name.getText();
        String Address = Dr_address.getText();
        String Specialization = Dr_specialization.getText();
        String Gender = Dr_gender.getSelectedItem().toString();
        String Experience = Dr_experience.getText();
        String Room = Dr_room.getText();
        String Email = Dr_email.getText();
        String Phone = Dr_phone.getText();
        try{
            st = con.createStatement();
            st.executeUpdate("Insert into doctor values('"+ID+"','"+Name+"','"+Address+"','"+Gender+"','"+Specialization+"','"+Experience+"','"+Room+"','"+Phone+"')");
            st.executeUpdate("Insert into doctoremail values('"+ID+"','"+Email+"')");
            JOptionPane.showMessageDialog(this, "Data Insertd Succecfully","Databse",JOptionPane.PLAIN_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Dr ID used more than once","Error",JOptionPane.ERROR_MESSAGE);
            
        }
                
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Doctor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
       
    }//GEN-LAST:event_DrSaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Dr_Id.setText("");
        Dr_name.setText("");
        Dr_address.setText("");
        Dr_specialization.setText("");
        Dr_gender.setSelectedIndex(0);
        Dr_experience.setText("");
        Dr_room.setText("");
        Dr_email.setText("");
        Dr_phone.setText("");
        Dr_name.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Dr_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dr_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dr_emailActionPerformed

    private void Dr_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dr_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dr_phoneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DrSave;
    private javax.swing.JTextField Dr_Id;
    private javax.swing.JTextField Dr_address;
    private javax.swing.JTextField Dr_email;
    private javax.swing.JTextField Dr_experience;
    private javax.swing.JComboBox<String> Dr_gender;
    private javax.swing.JTextField Dr_name;
    private javax.swing.JTextField Dr_phone;
    private javax.swing.JTextField Dr_room;
    private javax.swing.JTextField Dr_specialization;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
