/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nmc.nust.medical.centre;

import javafx.scene.layout.Pane;
import javafx.scene.Scene;
import javafx.scene.Node;


/**
 *
 * @author Rehan Ramzan
 */
public class NMC1 extends javax.swing.JFrame {

      //current user
    /**
     * Creates new form _2ndPage
     */
    private String name;
    private String password;
    private String Type; 
    public NMC1() {
        // Full Screen Image
        initComponents();
    }
  
    public NMC1(String name,String Type,String password){
        this.name = name;
        this.password = password;
        this.Type = Type;
        initComponents();
        jButton1.setText(name);
        
        if (Type.equals("Manager")){
           
            Patient.setVisible(false);
            Pharmacy.setVisible(false);
            Appointments.setVisible(false);
            Pharmacist.setVisible(false);
        }
        else if(Type.equals("Doctor"))
        {
            FG.setVisible(false);
            Patient.setVisible(false);
            Staff.setVisible(false);
            StaffRecord.setVisible(false);
            DoctorRecord.setVisible(false);
            Doctor.setVisible(false);
            Pharmacy.setVisible(false);
            Pharmacist.setVisible(false);
           
        }
        else if(Type.equals("Pharmacist"))
        {
           FG.setVisible(false);
           Patient.setVisible(false);
           PatientRecord.setVisible(false);
           Staff.setVisible(false);
           Appointments.setVisible(false);
           StaffRecord.setVisible(false);
           DoctorRecord.setVisible(false);
           Doctor.setVisible(false);
           Pharmacist.setVisible(false);
        }
        else if(Type.equals("Receptionist"))
        {
            FG.setVisible(false);
           PatientRecord.setVisible(false);
           StaffRecord.setVisible(false);
           DoctorRecord.setVisible(false);
           Appointments.setVisible(false);
           Doctor.setVisible(false);
           Staff.setVisible(false);
           Pharmacy.setVisible(false);
        }
        
        
    }
    
    
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Doctor = new javax.swing.JButton();
        Appointments = new javax.swing.JButton();
        Patient = new javax.swing.JButton();
        PatientRecord = new javax.swing.JButton();
        Staff = new javax.swing.JButton();
        Pharmacy = new javax.swing.JButton();
        DoctorRecord = new javax.swing.JButton();
        StaffRecord = new javax.swing.JButton();
        Information = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Pharmacist = new javax.swing.JButton();
        FG = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Doctor.setBackground(java.awt.SystemColor.controlShadow);
        Doctor.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        Doctor.setForeground(java.awt.SystemColor.windowBorder);
        Doctor.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\doctor.png")); // NOI18N
        Doctor.setText("Doctor");
        Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorActionPerformed(evt);
            }
        });
        getContentPane().add(Doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, 260, 75));

        Appointments.setBackground(java.awt.SystemColor.controlShadow);
        Appointments.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        Appointments.setForeground(java.awt.SystemColor.windowBorder);
        Appointments.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\appointments.png")); // NOI18N
        Appointments.setText("Show Appointmests");
        Appointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentsActionPerformed(evt);
            }
        });
        getContentPane().add(Appointments, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, 260, 75));

        Patient.setBackground(java.awt.SystemColor.controlShadow);
        Patient.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        Patient.setForeground(java.awt.SystemColor.windowBorder);
        Patient.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\patient.png")); // NOI18N
        Patient.setText(" Patient");
        Patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientActionPerformed(evt);
            }
        });
        getContentPane().add(Patient, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 660, 250, 75));

        PatientRecord.setBackground(java.awt.SystemColor.controlShadow);
        PatientRecord.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        PatientRecord.setForeground(java.awt.SystemColor.windowBorder);
        PatientRecord.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\patientRec.png")); // NOI18N
        PatientRecord.setText(" Patient Record");
        PatientRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientRecordActionPerformed(evt);
            }
        });
        getContentPane().add(PatientRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 660, 260, 75));

        Staff.setBackground(java.awt.SystemColor.controlShadow);
        Staff.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        Staff.setForeground(java.awt.SystemColor.windowBorder);
        Staff.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\steward.png")); // NOI18N
        Staff.setText(" Staff");
        Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffActionPerformed(evt);
            }
        });
        getContentPane().add(Staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, 260, 75));

        Pharmacy.setBackground(java.awt.SystemColor.controlShadow);
        Pharmacy.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        Pharmacy.setForeground(java.awt.SystemColor.windowBorder);
        Pharmacy.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\drugstore.png")); // NOI18N
        Pharmacy.setText(" Pharmacy");
        Pharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PharmacyActionPerformed(evt);
            }
        });
        getContentPane().add(Pharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 660, 250, 75));

        DoctorRecord.setBackground(java.awt.SystemColor.controlShadow);
        DoctorRecord.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        DoctorRecord.setForeground(java.awt.SystemColor.windowBorder);
        DoctorRecord.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\medical.png")); // NOI18N
        DoctorRecord.setText(" Doctor's Record");
        DoctorRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorRecordActionPerformed(evt);
            }
        });
        getContentPane().add(DoctorRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 550, 250, 75));

        StaffRecord.setBackground(java.awt.SystemColor.controlShadow);
        StaffRecord.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        StaffRecord.setForeground(java.awt.SystemColor.windowBorder);
        StaffRecord.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\medical-record.png")); // NOI18N
        StaffRecord.setText("  Staff's Record");
        StaffRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffRecordActionPerformed(evt);
            }
        });
        getContentPane().add(StaffRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 660, 250, 75));

        Information.setBackground(java.awt.SystemColor.controlShadow);
        Information.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        Information.setForeground(java.awt.SystemColor.windowBorder);
        Information.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\information.png")); // NOI18N
        Information.setText(" Information");
        Information.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformationActionPerformed(evt);
            }
        });
        getContentPane().add(Information, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 260, 75));

        Logout.setBackground(java.awt.SystemColor.controlShadow);
        Logout.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        Logout.setForeground(java.awt.SystemColor.windowBorder);
        Logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\exit.png")); // NOI18N
        Logout.setText(" Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, 260, 75));

        jButton1.setBackground(java.awt.SystemColor.controlShadow);
        jButton1.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jButton1.setForeground(java.awt.SystemColor.windowBorder);
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\man.png")); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 260, 75));

        Pharmacist.setBackground(java.awt.SystemColor.controlShadow);
        Pharmacist.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        Pharmacist.setForeground(java.awt.SystemColor.windowBorder);
        Pharmacist.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\pharmacist.png")); // NOI18N
        Pharmacist.setText("Pharmacist");
        Pharmacist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PharmacistActionPerformed(evt);
            }
        });
        getContentPane().add(Pharmacist, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, 260, 75));

        FG.setText("Forgot Password");
        FG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FGActionPerformed(evt);
            }
        });
        getContentPane().add(FG, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\home.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorActionPerformed
        new Doctor().setVisible(true);
     
        
    }//GEN-LAST:event_DoctorActionPerformed

    private void PatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientActionPerformed
        
        new Patient().setVisible(true);
    }//GEN-LAST:event_PatientActionPerformed

    private void PatientRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientRecordActionPerformed
        new PatientRecord().setVisible(true);
    }//GEN-LAST:event_PatientRecordActionPerformed

    private void StaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffActionPerformed
           new Staff().setVisible(true);
        
    }//GEN-LAST:event_StaffActionPerformed

    private void InformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformationActionPerformed
        new NMC_Information().setVisible(true);
    }//GEN-LAST:event_InformationActionPerformed

    private void DoctorRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorRecordActionPerformed
        new DoctorsRecord().setVisible(true);
    }//GEN-LAST:event_DoctorRecordActionPerformed

    private void StaffRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffRecordActionPerformed
        new StaffRecord().setVisible(true);
    }//GEN-LAST:event_StaffRecordActionPerformed

    private void AppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentsActionPerformed
        new Appointments().setVisible(true);
    }//GEN-LAST:event_AppointmentsActionPerformed

    private void PharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PharmacyActionPerformed
        new Pharmacy().setVisible(true);
    }//GEN-LAST:event_PharmacyActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_LogoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new user(name,password,Type).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PharmacistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PharmacistActionPerformed
        new Pharmacist().setVisible(true);
    }//GEN-LAST:event_PharmacistActionPerformed

    private void FGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FGActionPerformed
        new ForgotPassword().setVisible(true);
    }//GEN-LAST:event_FGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NMC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NMC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NMC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NMC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NMC1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Appointments;
    private javax.swing.JButton Doctor;
    private javax.swing.JButton DoctorRecord;
    private javax.swing.JButton FG;
    private javax.swing.JButton Information;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Patient;
    private javax.swing.JButton PatientRecord;
    private javax.swing.JButton Pharmacist;
    private javax.swing.JButton Pharmacy;
    private javax.swing.JButton Staff;
    private javax.swing.JButton StaffRecord;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
