/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package nmc.nust.medical.centre;

import Connection.MySqlConnection;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Rehan Ramzan
 */
public class Patient extends javax.swing.JFrame {

    /**
     * Creates new form AddAppointment
     */
     
    public Patient() {
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        semester = new javax.swing.JTextField();
        phostel = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        pcontactno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pgender = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        drId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        school = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel4.setForeground(java.awt.SystemColor.textHighlight);
        jLabel4.setText("Hostel");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 60, 30));

        jLabel5.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel5.setForeground(java.awt.SystemColor.textHighlight);
        jLabel5.setText("Contact No.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 130, 30));

        semester.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 250, 30));

        phostel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        phostel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ghazali", "Razi", "Hijveri", "Rumi", "Attar", "Zakaria", "Ayesha", "Khadija", "Zainab", "Fatima" }));
        getContentPane().add(phostel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 250, 30));

        jLabel7.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel7.setForeground(java.awt.SystemColor.textHighlight);
        jLabel7.setText("Patient ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 120, 30));

        pid.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 250, 30));

        pcontactno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(pcontactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 250, 30));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\Save.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, -1, 50));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\eraser (1).png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 60, 50));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\close.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 50, 40));

        jLabel6.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel6.setForeground(java.awt.SystemColor.textHighlight);
        jLabel6.setText("Gender");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, 30));

        pgender.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        pgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        getContentPane().add(pgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 250, 30));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel9.setForeground(java.awt.SystemColor.textHighlight);
        jLabel9.setText("Doctor ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, 40));

        drId.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        drId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drIdActionPerformed(evt);
            }
        });
        getContentPane().add(drId, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 250, 30));

        jLabel10.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel10.setForeground(java.awt.SystemColor.textHighlight);
        jLabel10.setText("Semester ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 90, 30));

        jLabel11.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel11.setForeground(java.awt.SystemColor.textHighlight);
        jLabel11.setText("Patient name ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 140, 30));

        pname.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 250, 30));

        jLabel12.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel12.setForeground(java.awt.SystemColor.textHighlight);
        jLabel12.setText("School ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 70, 30));

        school.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(school, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 250, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\Screen.jpg")); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection con = MySqlConnection.Connect();
        Statement st;
        String id = pid.getText();
        String name = pname.getText();
        String hostel = phostel.getSelectedItem().toString();
        String gender = pgender.getSelectedItem().toString();
        String contactno = pcontactno.getText();
        String Dr_Id = drId.getText();
        String School = school.getText();
        String Semester = semester.getText();
        try{
        st = con.createStatement();
        st.executeUpdate("Insert into patientrecord values ('"+id+"','"+name+"','"+hostel+"','"+gender+"','"+School+"','"+Semester+"')");
        st.executeUpdate("Insert into patientappoint(Patient_id,Doctor_id,Contact_No) values('"+id+"','"+Dr_Id+"','"+contactno+"')");
        JOptionPane.showMessageDialog(this, "Appointment  Fixed.","Database",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Patient ID is used more than once","Alert",JOptionPane.WARNING_MESSAGE);
        }
        
        try {
            con.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pid.setText("");
        school.setText("");
        semester.setText("");
        phostel.setSelectedIndex(0);
        pgender.setSelectedIndex(0);
        pname.setText("");
        pcontactno.setText("");
        drId.setText("");
        pid.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void drIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField drId;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField pcontactno;
    private javax.swing.JComboBox<String> pgender;
    private javax.swing.JComboBox<String> phostel;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField school;
    private javax.swing.JTextField semester;
    // End of variables declaration//GEN-END:variables
}
