/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nmc.nust.medical.centre;

import Connection.MySqlConnection;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Rehan Ramzan
 */
public class Prescription extends javax.swing.JFrame {

    /**
     * Creates new form Prescription
     */
    public Prescription() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        driving = new javax.swing.JTextField();
        sideeffects = new javax.swing.JTextField();
        noofdays = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        dailydose5 = new javax.swing.JTextField();
        avoidthings = new javax.swing.JTextField();
        recdate = new javax.swing.JTextField();
        tablet4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tablet1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tablet2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        dailydose2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tablet3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        dailydose3 = new javax.swing.JTextField();
        dailydose4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        medication = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        mess = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        dailydose0 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        recommend = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReciptText = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setBackground(java.awt.SystemColor.text);
        jPanel2.setForeground(java.awt.SystemColor.controlLtHighlight);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.textHighlight);
        jLabel3.setText("No Of Days");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.SystemColor.textHighlight);
        jLabel4.setText("SideEffects");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.SystemColor.textHighlight);
        jLabel5.setText("     Driving ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(java.awt.SystemColor.textHighlight);
        jLabel6.setText("   ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.SystemColor.textHighlight);
        jLabel7.setText("Avoid Things");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 110, 30));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(java.awt.SystemColor.textHighlight);
        jLabel9.setText("Daily Dose");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 80, 20));
        getContentPane().add(driving, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 340, 30));

        sideeffects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideeffectsActionPerformed(evt);
            }
        });
        getContentPane().add(sideeffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 340, 30));
        getContentPane().add(noofdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 340, 30));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 189, -1, -1));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 70, 30));
        getContentPane().add(dailydose5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 110, 23));
        getContentPane().add(avoidthings, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 340, 30));
        getContentPane().add(recdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 110, 25));

        tablet4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablet4ActionPerformed(evt);
            }
        });
        getContentPane().add(tablet4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 150, 23));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setForeground(java.awt.SystemColor.textHighlight);
        jLabel13.setText("Tablet 1");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        getContentPane().add(tablet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 150, 23));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setForeground(java.awt.SystemColor.textHighlight);
        jLabel14.setText("Daily Dose");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 80, 20));

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel15.setForeground(java.awt.SystemColor.textHighlight);
        jLabel15.setText("Tablet 2");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        getContentPane().add(tablet2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 150, 23));

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel16.setForeground(java.awt.SystemColor.textHighlight);
        jLabel16.setText("Daily Dose");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 80, 20));

        dailydose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailydose2ActionPerformed(evt);
            }
        });
        getContentPane().add(dailydose2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 110, 23));

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel17.setForeground(java.awt.SystemColor.textHighlight);
        jLabel17.setText("Tablet 3");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        getContentPane().add(tablet3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 150, 23));

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel18.setForeground(java.awt.SystemColor.textHighlight);
        jLabel18.setText("Daily Dose");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 80, 20));
        getContentPane().add(dailydose3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 110, 23));
        getContentPane().add(dailydose4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 110, 23));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setForeground(java.awt.SystemColor.textHighlight);
        jLabel12.setText("Medication");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 90, 30));
        getContentPane().add(medication, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 340, 30));

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel19.setForeground(java.awt.SystemColor.textHighlight);
        jLabel19.setText("Hostel Mess");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 30));
        getContentPane().add(mess, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 340, 30));

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel20.setForeground(java.awt.SystemColor.textHighlight);
        jLabel20.setText("Date/Time ");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 90, 30));

        dailydose0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailydose0ActionPerformed(evt);
            }
        });
        getContentPane().add(dailydose0, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 110, 23));

        jLabel21.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel21.setForeground(java.awt.SystemColor.textHighlight);
        jLabel21.setText("Recommended ");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 130, 30));
        getContentPane().add(recommend, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 110, 25));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\receipt.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 60, 50));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\close.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 50, -1));

        ReciptText.setColumns(20);
        ReciptText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ReciptText.setRows(5);
        jScrollPane1.setViewportView(ReciptText);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 420, 450));

        jPanel3.setBackground(java.awt.SystemColor.window);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.textHighlight);
        jLabel1.setText("Syrup");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sideeffectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideeffectsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sideeffectsActionPerformed

    private void dailydose0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailydose0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dailydose0ActionPerformed

    private void dailydose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailydose2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dailydose2ActionPerformed

    private void tablet4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablet4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tablet4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection con = MySqlConnection.Connect();
        String ID = id.getText();
        String Tablet1 = tablet1.getText();
        String DailyDose1 = dailydose0.getText();
        String Tablet2 = tablet2.getText();
        String DailyDose2 = dailydose2.getText();
        String Tablet3 = tablet3.getText();
        String DailyDose3 = dailydose3.getText();
        String Tablet4 = tablet4.getText();
        String DailyDose4 = dailydose5.getText();
        String Days = noofdays.getText();
        String SideEffects = sideeffects.getText();
        String Driving = driving.getText();
        String Medication = medication.getText();
        String Avoid = avoidthings.getText();
        String Mess = mess.getText();
        String Recomend = recommend.getText();
        String RecDate = recdate.getText();
        try{
            Statement st = con.createStatement();
            st.executeUpdate("Insert into prescription(ID,Tablet1,Tablet2,Tablet3,Tablet4,Noofdays)values ('"+ID+"','"+Tablet1+"','"+Tablet2+"','"+Tablet3+"','"+Tablet4+"','"+Days+"')");
            ReciptText.append("\n\t            NUST MEDICAL CENTRE\n\n\n   Patient ID   : "+"\t"+ID+"\n\n   Tablet1\t\t"+Tablet1+
                "\tDaily Dose\t"+DailyDose1+"\n\n   Tablet2\t\t"+Tablet2+"\tDaily Dose\t"+DailyDose2+"\n\n   Tablet3\t\t"+Tablet3+"\tDaily Dose\t"+DailyDose3+
                "\n\n   Tablet4\t\t"+Tablet4+"\tDaily Dose\t"+DailyDose4+"\n\n   No Of Days\t\t"+Days+
                "\n\n   Side Effects\t\t"+SideEffects+"\n\n   Driving\t\t"+Driving+"\n\n   Medication\t\t"+Medication+
                "\n\n   Avoid Use\t\t"+Avoid+"\n\n    Hostel Mess\t\t"+Mess+"\n\n    Recommended To \t"+Recomend+
                "\n\n    Recomemnd Date \t"+RecDate+
                "\n\n  Please  keep  this  prescription  with  yourself  and  take  care!\n\n\n\t\t\t  Thanks");

        }

        catch(Exception e){
            System.out.println(e);
        }

        id.setText("");
        tablet1.setText("");
        tablet2.setText("");
        tablet3.setText("");
        tablet4.setText("");
        dailydose0.setText("");
        dailydose2.setText("");
        dailydose3.setText("");
        dailydose5.setText("");
        noofdays.setText("");
        sideeffects.setText("");
        mess.setText("");
        driving.setText("");
        avoidthings.setText("");
        medication.setText("");
        recommend.setText("");
        recdate.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prescription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ReciptText;
    private javax.swing.JTextField avoidthings;
    private javax.swing.JTextField dailydose0;
    private javax.swing.JTextField dailydose2;
    private javax.swing.JTextField dailydose3;
    private javax.swing.JTextField dailydose4;
    private javax.swing.JTextField dailydose5;
    private javax.swing.JTextField driving;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField medication;
    private javax.swing.JTextField mess;
    private javax.swing.JTextField noofdays;
    private javax.swing.JTextField recdate;
    private javax.swing.JTextField recommend;
    private javax.swing.JTextField sideeffects;
    private javax.swing.JTextField tablet1;
    private javax.swing.JTextField tablet2;
    private javax.swing.JTextField tablet3;
    private javax.swing.JTextField tablet4;
    // End of variables declaration//GEN-END:variables
}
