/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nmc.nust.medical.centre;
import Connection.MySqlConnection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rehan Ramzan
 */
   

public class Staff extends javax.swing.JFrame {

    /**
     * Creates new form Page_StaffRecord
     */
     

    public Staff() {
      
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Staff_name = new javax.swing.JTextField();
        Staff_id = new javax.swing.JTextField();
        Staff_email = new javax.swing.JTextField();
        Staff_contact = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Staff_gender = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.textHighlight);
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, 30));

        jLabel2.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.textHighlight);
        jLabel2.setText("Staff ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, 30));

        jLabel3.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.textHighlight);
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, 40));

        jLabel4.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel4.setForeground(java.awt.SystemColor.textHighlight);
        jLabel4.setText("Contact No.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, 40));

        Staff_name.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(Staff_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 200, -1));

        Staff_id.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(Staff_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 200, -1));

        Staff_email.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(Staff_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 200, -1));

        Staff_contact.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Staff_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Staff_contactActionPerformed(evt);
            }
        });
        getContentPane().add(Staff_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 200, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\Save.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 441, -1, 50));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\eraser (1).png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, -1, 50));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\close.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 50, -1));

        jLabel7.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel7.setForeground(java.awt.SystemColor.textHighlight);
        jLabel7.setText("Gender");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        Staff_gender.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Staff_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(Staff_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 200, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\NMC(Nust Medical Centre)\\HMS ICONS\\Screen.jpg")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection con = MySqlConnection.Connect();
        String Name = Staff_name.getText();
        String ID = Staff_id.getText();
         PreparedStatement pst;
        try {
            pst = con.prepareStatement("Select * from doctor where DoctorID = ?");
              pst.setString(1, ID);
            ResultSet r = pst.executeQuery();
            if(r.next()){
                JOptionPane.showMessageDialog(this,"ID in Use.","Error",JOptionPane.ERROR_MESSAGE);
                Staff_id.setText("");
            }
            else{
                  
        
        String Gender = Staff_gender.getSelectedItem().toString();
        String Email = Staff_email.getText();
        String Contact = Staff_contact.getText();
        
        try{
        Statement st = con.createStatement();
        st.executeUpdate("Insert into Staff values('"+ID+"','"+Name+"','"+Gender+"')");
        st.executeUpdate("Insert into Staffcontacts values('"+Email+"','"+Contact+"','"+ID+"')");
        JOptionPane.showMessageDialog(this, "Data Inserted Successfully","Database",JOptionPane.PLAIN_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Staff ID used more than once","Error",JOptionPane.ERROR_MESSAGE);
        } 
                
                
      
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Staff.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        
        
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Staff_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Staff_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Staff_contactActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Staff_name.setText("");
        Staff_id.setText("");
        Staff_gender.setSelectedIndex(0);
        Staff_email.setText("");
        Staff_contact.setText("");
        Staff_id.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Staff_contact;
    private javax.swing.JTextField Staff_email;
    private javax.swing.JComboBox<String> Staff_gender;
    private javax.swing.JTextField Staff_id;
    private javax.swing.JTextField Staff_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
